- name: frontend
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove default content in html 
    ansible.builtin.file:
       path: /usr/share/nginx/html/*
       state: absent

  - name: remove default content in html 
    ansible.builtin.file:
       path: /usr/share/nginx/html/
       state: directory

  - name: Download the frontend content and extract 
    ansible.builtin.unarchive:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  # - name: Extract application
  #   ansible.builtin.unarchive:
  #     src: /tmp/frontend.zip
  #     dest: /usr/share/nginx/html
  #     remote_src: yes

  - name: copy expense configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


  
